across:
  development:
    active: true

applicationInfo:
  buildDate: "2022-09-01 15:13:48"

server:
  error:
    includeStacktrace: ALWAYS
  port: 8080

spring:
  datasource:
    url: "jdbc:h2:./local-data/db/prep-db"
    username: sa

